const translations = {
    en: {
        title: "Resume of Maixiu",
        name: "Maixiu (Senior R&D Engineer)",
        gender: "Gender:",
        dob: "Date of Birth:",
        location: "Location:",
        politicalStatus: "Political Status:",
        website: "Personal Website:",
        phone: "Phone:",
        email: "Email:",
        github: "GitHub:",
        education: "Education Background",
        university1: "Southwest ** University (Regular Enrollment - 211) - Master's - ***",
        eduPeriod1: "Sep 2014 - Jun 2017",
        university2: "** University of Science and Technology (Regular Enrollment - General) - Bachelor's - ***",
        eduPeriod2: "Sep 2010 - Jun 2014",
        skills: "Professional Skills",
        skill1: "Computer Basics: Familiar with computer networks, operating systems, data structures, and algorithms.",
        skill2: "Java: Solid Java foundation; proficient in JVM tuning, multithreading programming, and functional programming. Frameworks: Proficient in using and understanding the principles of the Spring family and ORM frameworks.",
        skill3: "Database: Proficient in database design, database optimization (SQL optimization, DB optimization, architecture optimization), connection pool usage and tuning, and data migration.",
        skill4: "Design: Proficient in design patterns, capable of business abstraction.",
        skill5: "AI: Familiar with the latest AI technologies, API calls; proficient in using AI to assist in design and coding.",
        skill6: "Linux: Familiar with the Linux operating system, shell programming; proficient in deploying applications on Linux, analyzing anomalies, and troubleshooting performance issues; proficient in shell text processing.",
        skill7: "Frontend: Proficient in JavaScript frontend development; familiar with HTML and CSS.",
        skill8: "Tools: Proficient in Nginx proxy configuration; familiar with Docker container technology and usage.",
        skill9: "Xinchuang: Familiar with domestic Xinchuang software, proficient in solving Xinchuang adaptation issues.",
        experience: "Work Experience",
        company: "***** Technology Co., Ltd. - R&D Center - Senior R&D Engineer",
        workPeriod: "Jul 2017 - *****",
        responsibility1: "Architecture design technical selection, overall module outline design, core module detailed design, interface design, database design, specific problem technical solution design",
        responsibility2: "Basic common module development, new project framework development, core difficult module development, adaptation development (interface/data/Xinchuang)",
        responsibility3: "Online troubleshooting of difficult bugs, pre-research and tackling of team technical difficulties, performance problem troubleshooting",
        responsibility4: "Team technical division and collaboration, estimation of R&D man-hours and project costs, control of R&D delivery progress",
        responsibility5: "On-site deployment and implementation, Nginx proxy, system migration, network transformation adaptation",
        projects: "Projects",
        project1Title: "AI Exchange",
        techStack: "Tech Stack:",
        project1Summary: "AI-driven, natural language input to boost productivity in text conversion, image generation, and intelligent reading.",
        responsibilities: "Responsibilities:",
        project1Resp1: "Backend task multi-threading design (supports delay, retry, queuing, etc.)",
        project1Resp2: "AI interface calls, fault tolerance handling, channel switching",
        project1Resp3: "Sandbox operation security implementation (call time, output length, resource access)",
        project1Resp4: "Frontend page design and development",
        project2Title: "*****",
        project2Summary: "Realize online collaborative handling of cases across departments in Guangzhou's legal units.",
        project2Resp1: "Overall application deployment and network exchange solution design",
        project2Resp2: "** sub-platform packaging service design and development",
        project2Resp3: "Exchange subsystem design and development",
        project2Resp4: "Data packet platform circulation **",
        project2Resp5: "** subsystem design and development",
        project3Title: "*****",
        project3Summary: "Based on **** data statistical analysis system, display and warn business indicators, assist *** and decision-making.",
        project3Resp1: "Project infrastructure construction",
        project3Resp2: "General module design (for statistical charts)",
        project3Resp3: "** statistical analysis and database design",
        project3Resp4: "Adaptation and transformation of Dameng national database",
        project3Resp5: "Performance optimization",
        project4Title: "*****",
        project4Summary: "Realize the collection, processing, and import of structured and semi-structured data. Support multi-threaded large-scale data batch processing, support SQL execution, runtime scripts, SSH collection, and other components.",
        project4Resp1: "Backend collection task framework construction",
        project4Resp2: "Backend database design",
        project4Resp3: "Data processing core module design and development",
        project4Resp4: "Multi-data source adaptation scheme design and implementation",
        tech1: "AI chatgpt",
        tech2: "HTTPS",
        tech3: "Nginx",
        tech4: "Multithreading",
        tech5: "Cross-domain",
        tech6: "Reverse Proxy",
        tech7: "Regex",
        tech8: "GarrlVM",
        tech9: "js",
        tech10: "python",
        tech11: "springboot",
        tech12: "mybatis-plus",
        tech13: "layui",
        tech14: "Multithreading",
        tech15: "HTTPS",
        tech16: "Signature Mutual Trust",
        tech17: "Gson",
        tech18: "Cross-domain",
        tech19: "RocksDB",
        tech20: "Minion",
        tech21: "Nginx",
        tech22: "SM4",
        tech23: "Renmin Jincang",
        tech24: "SSO",
        tech25: "Design Patterns",
        tech26: "Performance Optimization",
        tech27: "Interface Design",
        tech28: "Caching",
        tech29: "Multithreading",
        tech30: "Log Visualization"
    },
    cn: {
        title: "麦秀的简历",
        name: "麦秀（高级研发工程师）",
        gender: "性别：",
        dob: "出生日期：",
        location: "所在地：",
        politicalStatus: "政治面貌：",
        website: "个人网站：",
        phone: "电话：",
        email: "邮箱：",
        github: "GitHub：",
        education: "教育背景",
        university1: "西南**大学（统招-211） - 硕士 - ***",
        eduPeriod1: "2014.09 - 2017.06",
        university2: "**科技大学（统招-普本） - 学士 - ***",
        eduPeriod2: "2010.09 - 2014.06",
        skills: "专业技能",
        skill1: "计算机基础：熟悉计算机网络、操作系统、数据结构和算法。",
        skill2: "Java：Java基础扎实；掌握JVM调优、多线程编程、函数式编程。框架：熟练掌握Spring家族、ORM框架使用及原理。",
        skill3: "数据库：掌握数据库设计、数据库优化（SQL优化、DB优化、架构优化）、连接池使用和调优、数据迁移。",
        skill4: "设计：掌握设计模式，具备业务抽象能力。",
        skill5: "AI: 熟悉最新AI技术、API调用；熟练利用AI辅助做设计、写代码。",
        skill6: "Linux：熟悉Linux操作系统、Shell编程；掌握Linux部署应用异常分析、性能问题排查；掌握Shell文本处理。",
        skill7: "前端：掌握JavaScript前端开发；熟悉HTML、CSS。",
        skill8: "工具：掌握Nginx代理配置；熟悉Docker容器技术及使用。",
        skill9: "信创：熟悉国产信创软件，掌握信创适配问题解决。",
        experience: "工作经历",
        company: "*****技术有限公司 - 研发中心 - 高级研发工程师",
        workPeriod: "2017.07 - *****",
        responsibility1: "架构设计技术选型、总体模块概要设计、核心模块详细设计、接口设计、数据库设计、特定问题技术方案设计",
        responsibility2: "基础公用模块开发、新项目框架开发、核心难点模块开发、适配开发（对接/数据/信创）",
        responsibility3: "线上疑难bug排查、团队技术难点预研攻关、性能问题排查",
        responsibility4: "团队内技术分工与协作、估算研发工时和项目成本、管控研发交付进度",
        responsibility5: "现场部署实施、Nginx代理、系统迁移、网络改造适配",
        projects: "项目",
        project1Title: "AI Exchange",
        techStack: "技术栈：",
        project1Summary: "AI驱动，自然语言为输入，激发文本转换、图片生成、智能阅读等生产效率。",
        responsibilities: "负责内容：",
        project1Resp1: "后端任务多线程设计（支持延迟、重试、排队等）",
        project1Resp2: "AI接口调用、容错处理、渠道切换",
        project1Resp3: "沙盒运行安全实现（调用时间、输出长度、资源访问）",
        project1Resp4: "前端页面设计开发",
        project2Title: "*****",
        project2Summary: "实现广州市、区政法单位案件跨部门网上协同办理。",
        project2Resp1: "总体应用部署及网络交换方案设计",
        project2Resp2: "**分平台打包服务设计和开发",
        project2Resp3: "交换子系统设计和开发",
        project2Resp4: "数据包平台流转**",
        project2Resp5: "**子系统设计和开发",
        project3Title: "*****",
        project3Summary: "基于****数据统计分析系统，展示并预警业务指标，辅助***和决策。",
        project3Resp1: "项目基础架构搭建",
        project3Resp2: "通用模块设计（针对统计图）",
        project3Resp3: "**统计分析及数据库设计",
        project3Resp4: "达梦国产数据库适配改造",
        project3Resp5: "性能优化",
        project4Title: "*****",
        project4Summary: "实现结构化、半结构数据的采集、处理和导入。支持多线程大规模数据的批处理，支持SQL执行、运行时脚本、SSH采集等多组件。",
        project4Resp1: "后端采集任务框架搭建",
        project4Resp2: "后端数据库设计",
        project4Resp3: "数据处理核心模块设计和开发",
        project4Resp4: "多数据源适配方案设计及实现",
        tech1: "AI chatgpt",
        tech2: "HTTPS",
        tech3: "Nginx",
        tech4: "多线程",
        tech5: "跨域",
        tech6: "反向代理",
        tech7: "Regex",
        tech8: "GarrlVM",
        tech9: "js",
        tech10: "python",
        tech11: "springboot",
        tech12: "mybatis-plus",
        tech13: "layui",
        tech14: "多线程",
        tech15: "HTTPS",
        tech16: "签章互信",
        tech17: "Gson",
        tech18: "跨域",
        tech19: "RocksDB",
        tech20: "Minion",
        tech21: "Nginx",
        tech22: "SM4",
        tech23: "人大金仓",
        tech24: "SSO",
        tech25: "设计模式",
        tech26: "性能优化",
        tech27: "接口设计",
        tech28: "缓存",
        tech29: "多线程",
        tech30: "日志可视化"
    }
};